version: "3"
services:
  influxdb:
    image: influxdb:2.0.7
    ports:
      - "8086:8086"
    volumes:
      - influxdbv2:/var/lib/influxdb2
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.0.7
    entrypoint: influx setup --bucket ${DOCKER_INFLUXDB_INIT_BUCKET} -t ${DOCKER_INFLUXDB_TOKEN} -o ${DOCKER_INFLUXDB_INIT_ORG} --username=${DOCKER_INFLUXDB_INIT_USERNAME} --password=${DOCKER_INFLUXDB_INIT_PASSWORD} --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
  server:
    image: weather-station-alpine:1
    restart: on-failure:10
    depends_on:
      - influxdb
      - influxdb_cli
volumes:
  influxdbv2:
